version: "3.0"
name: bolt_sips

services:
  neo4j-3.4.0:
    image: neo4j:3.4.0
    labels:
        - "boltVersions=1.0,2.0"
        - "database=neo4j"
    ports:
      - 7688:7687
    environment:
      - NEO4J_AUTH=neo4j/BoltSipsPassword
      - NEO4J_dbms_mode=CORE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_connector_bolt_listen__address=:7687
  neo4j-4.4:
    image: neo4j:4.4-community
    labels:
        - "boltVersions=3.0,4.0,4.1,4.2,4.3,4.4"
        - "database=neo4j"
    ports:
      - 7689:7687
    environment:
      - NEO4J_AUTH=neo4j/BoltSipsPassword
  neo4j-5.12.0:
    image: neo4j:5.12.0-community
    labels:
        - "boltVersions=5.0,5.1,5.2,5.3"
        - "database=neo4j"
    ports:
      - 7690:7687
    environment:
      - NEO4J_AUTH=neo4j/BoltSipsPassword
  memgraph-2.11.0:
    image: "memgraph/memgraph:2.11.0"
    labels:
        - "boltVersions=5.0,5.1,5.2"
        - "database=memgraph"
    ports:
      - "7691:7687"
    entrypoint: ["/usr/lib/memgraph/memgraph", "--log-level=TRACE"]
